//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoansItemMvc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YCUserDetailsData", Namespace="http://schemas.datacontract.org/2004/07/MyDome.Model")]
    [System.SerializableAttribute()]
    public partial class YCUserDetailsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TempNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempNum1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Ud_AuditIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_GoalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ud_IDCardPicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_IdentityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ud_MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ud_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ud_NowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ud_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ud_RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Ud_SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ud_UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TempNum {
            get {
                return this.TempNumField;
            }
            set {
                if ((this.TempNumField.Equals(value) != true)) {
                    this.TempNumField = value;
                    this.RaisePropertyChanged("TempNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempNum1 {
            get {
                return this.TempNum1Field;
            }
            set {
                if ((this.TempNum1Field.Equals(value) != true)) {
                    this.TempNum1Field = value;
                    this.RaisePropertyChanged("TempNum1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ud_AuditId {
            get {
                return this.Ud_AuditIdField;
            }
            set {
                if ((this.Ud_AuditIdField.Equals(value) != true)) {
                    this.Ud_AuditIdField = value;
                    this.RaisePropertyChanged("Ud_AuditId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_BillId {
            get {
                return this.Ud_BillIdField;
            }
            set {
                if ((this.Ud_BillIdField.Equals(value) != true)) {
                    this.Ud_BillIdField = value;
                    this.RaisePropertyChanged("Ud_BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_Goal {
            get {
                return this.Ud_GoalField;
            }
            set {
                if ((this.Ud_GoalField.Equals(value) != true)) {
                    this.Ud_GoalField = value;
                    this.RaisePropertyChanged("Ud_Goal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ud_IDCardPic {
            get {
                return this.Ud_IDCardPicField;
            }
            set {
                if ((object.ReferenceEquals(this.Ud_IDCardPicField, value) != true)) {
                    this.Ud_IDCardPicField = value;
                    this.RaisePropertyChanged("Ud_IDCardPic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_Id {
            get {
                return this.Ud_IdField;
            }
            set {
                if ((this.Ud_IdField.Equals(value) != true)) {
                    this.Ud_IdField = value;
                    this.RaisePropertyChanged("Ud_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_IdentityID {
            get {
                return this.Ud_IdentityIDField;
            }
            set {
                if ((this.Ud_IdentityIDField.Equals(value) != true)) {
                    this.Ud_IdentityIDField = value;
                    this.RaisePropertyChanged("Ud_IdentityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ud_Money {
            get {
                return this.Ud_MoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.Ud_MoneyField, value) != true)) {
                    this.Ud_MoneyField = value;
                    this.RaisePropertyChanged("Ud_Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ud_Name {
            get {
                return this.Ud_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Ud_NameField, value) != true)) {
                    this.Ud_NameField = value;
                    this.RaisePropertyChanged("Ud_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ud_NowDate {
            get {
                return this.Ud_NowDateField;
            }
            set {
                if ((this.Ud_NowDateField.Equals(value) != true)) {
                    this.Ud_NowDateField = value;
                    this.RaisePropertyChanged("Ud_NowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ud_Phone {
            get {
                return this.Ud_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Ud_PhoneField, value) != true)) {
                    this.Ud_PhoneField = value;
                    this.RaisePropertyChanged("Ud_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ud_Remark {
            get {
                return this.Ud_RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.Ud_RemarkField, value) != true)) {
                    this.Ud_RemarkField = value;
                    this.RaisePropertyChanged("Ud_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ud_Sex {
            get {
                return this.Ud_SexField;
            }
            set {
                if ((this.Ud_SexField.Equals(value) != true)) {
                    this.Ud_SexField = value;
                    this.RaisePropertyChanged("Ud_Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_Time {
            get {
                return this.Ud_TimeField;
            }
            set {
                if ((this.Ud_TimeField.Equals(value) != true)) {
                    this.Ud_TimeField = value;
                    this.RaisePropertyChanged("Ud_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_Type {
            get {
                return this.Ud_TypeField;
            }
            set {
                if ((this.Ud_TypeField.Equals(value) != true)) {
                    this.Ud_TypeField = value;
                    this.RaisePropertyChanged("Ud_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_TypeId {
            get {
                return this.Ud_TypeIdField;
            }
            set {
                if ((this.Ud_TypeIdField.Equals(value) != true)) {
                    this.Ud_TypeIdField = value;
                    this.RaisePropertyChanged("Ud_TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ud_UserId {
            get {
                return this.Ud_UserIdField;
            }
            set {
                if ((this.Ud_UserIdField.Equals(value) != true)) {
                    this.Ud_UserIdField = value;
                    this.RaisePropertyChanged("Ud_UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdd")]
    public interface IAdd {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdd/DoWork", ReplyAction="http://tempuri.org/IAdd/DoWorkResponse")]
        bool DoWork(LoansItemMvc.ServiceReference1.YCUserDetailsData yCUserD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdd/DoWork", ReplyAction="http://tempuri.org/IAdd/DoWorkResponse")]
        System.Threading.Tasks.Task<bool> DoWorkAsync(LoansItemMvc.ServiceReference1.YCUserDetailsData yCUserD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddChannel : LoansItemMvc.ServiceReference1.IAdd, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddClient : System.ServiceModel.ClientBase<LoansItemMvc.ServiceReference1.IAdd>, LoansItemMvc.ServiceReference1.IAdd {
        
        public AddClient() {
        }
        
        public AddClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DoWork(LoansItemMvc.ServiceReference1.YCUserDetailsData yCUserD) {
            return base.Channel.DoWork(yCUserD);
        }
        
        public System.Threading.Tasks.Task<bool> DoWorkAsync(LoansItemMvc.ServiceReference1.YCUserDetailsData yCUserD) {
            return base.Channel.DoWorkAsync(yCUserD);
        }
    }
}
